### ISSUE TITLE
[ISSUE] CharacterTrajectories includes missing vals but .csv doesn't agree; DDGS missing data for dim 271

### ISSUE THREAD

**Issue by jasonlines** [uea-machine-learning/tsml_repo#25]
(Issue raised externally by email - summarising here)

**Which dataset/datasets have you an issue with?**
CharacterTrajectories,  DuckDuckGeeseDimension271_TEST.arff 

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)? **
tsc (I believe)

**Whats the issue?**

The summaryMultivariate.csv file indicates that the CharacterTrajectories dataset doesn't have any MissingValues, but analyzing it further, I found time windows in which only one of the variables of the multivariable time series has unknown values. I include a csv per feature where I indicate each NA index of the time series and the instants of time in which they appear. (4 Files: 2 Train and 2 Test, Dimension 1 and 2)

For example, in the training set, for dimension 1, the time series 159 contains NA values from time instant 89 to 99.

Regarding data files, I found that the file DuckDuckGeeseDimension271_TEST.arff is empty. (DuckDuckGeeseDimension271_TRAIN.arff contains data).

**Comment by fjbaldan** [comment]
Hi Jason, that's right, I downloaded it from http://www.timeseriesclassification.com/Downloads/Archives/Multivariate2018_arff.zip.
Just let me know if you need any additional information.

**Comment by jasonlines** [comment]
Ah brilliant, thanks for the extra info. And thanks for your email Francisco - having a frantic day so haven't had a chance to reply but wanted at least put your issue on here so we don't miss it :) we'll keep you updated when we get a chance to look into it. 

Thanks,

Jason

**Comment by TonyBagnall** [comment]
cheers for this, I'll put it on the list and hopefully we will sort this out next week

**Comment by fjbaldan** [comment]
Another interesting point I'd like to comment on datasets: CharacterTrajectories, JapaneseVowels and SpokenArabicDigits. These datasets have NA sequences of different lengths at the end of the time series, between the data and the label of each time series (the amount of NA is the same for all variables of the same time series). I understand that the original time series have different lengths and these NA are used so that they all have the same length. Thanks to this we can use fixed dimension structures such as data frames. Could this be included in the summaryMultivariate.csv file in the Padded column (or even in the MissingValues column)?

**Comment by TonyBagnall** [comment]
DuckDuckGeese now fixed, will get round to the other one soon, thanks.

**Comment by TonyBagnall** [comment]
sorry, forgot to close this. CharacterTrajectories, JapaneseVowels and SpokenArabicDigits are unequal length problems with padding added to allow arff format. Hopefully made this clearer.
